# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff61f7eedaa4a6f6d5ee941b11eb87dbb318a58bbc679141817bd5bdb95261734cb67ce697a23b01e6758b5a0427e64f9d13220c68d95dab63bbd4bbd36aef51

test:
  secret_key_base: d615b0ff0c8e24be8534123c5f875f5831d76eea676673376ae8a5e6490ecf09003552692517ba53f269258a34bf320ee838691d88846060fd4ceb86c068b672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
